### ISSUE TITLE
Dropping in a folder gives raw file object, should give all nested files object to onCreateFiles

### ISSUE THREAD

**Issue by ziaulrehman40** [uptick/react-keyed-file-browser#109]
`onCreateFiles` gets called with a file object with only folder name and some other attributes, which is not useable(as far as i know).

If a folder is dropped, all files in the folder should be returned, or some other way user should at-least be able to process the folder for the upload.

**Comment by jlo-1** [comment]
Closing due to being fixed in https://github.com/uptick/react-keyed-file-browser/pull/110
