### ISSUE TITLE
Add demo for thumbnail list view.

### ISSUE THREAD

**Issue by jarekwg** [uptick/react-keyed-file-browser#11]

**Comment by shaibe** [comment]
Is this something which is planned soon? I've noticed that there is some code (RawListThumbnailFile) already in progress....

**Comment by jarekwg** [comment]
Hi shaibe,

Yep, can't give you a timeframe, but hopefully within the next month or so? We already use the thumbnail renderer in our production code, just have to get round to finishing stripping it out of our code and plonking it into this package..

Cheers,

**Comment by shaibe** [comment]
Thanks for the response!

--Shai
