### ISSUE TITLE
How to download the file? or view content of a file?

### ISSUE THREAD

**Issue by arlandgoh** [uptick/react-keyed-file-browser#113]

**Comment by jarekwg** [comment]
See #33. Your detail renderer can include a download button. If you want a download option directly from file browser, perhaps something can be done using custom actions.

**Comment by jestrickler** [comment]
It's part of the built in actions. You just have to supply a handler to enable it onDownloadFile={...}. Ours makes a service call, the calls js-file-download with the results.
