### ISSUE TITLE
How to use using JSX?

### ISSUE THREAD

**Issue by nerdogram** [uptick/react-keyed-file-browser#117]
Noob question but I am having difficulty implementing the basic example using JSX?

```
import React from 'react'
import FileBrowser from 'react-keyed-file-browser'

const FileBrowserComponent = () => {
 const data = [] //example data
 return (
 <FileBrowser
    files={data}
  />
 )
};

export default FileBrowserComponent;
```

How do you make this work? Thanks!

**Comment by dreadera** [comment]
Apologies for taking so long to get back to you. If you follow the examples on the [demo-site](https://uptick.github.io/react-keyed-file-browser/) with a valid react environment. It should work out of the box. 

If you are still stuck, feel free to create a new issue!
I'll be closing this as a part of cleaning up.
