### ISSUE TITLE
how to display empty folders.

### ISSUE THREAD

**Issue by santoshkanuri** [uptick/react-keyed-file-browser#121]
Hi flocks, 
    is there any way to display empty folders. 
Thanks in advice.

**Comment by jestrickler** [comment]
Not sure what you mean. Empty folders display fine by default: (2020 Docs is empty)

<img width="157" alt="Screen Shot 2020-09-29 at 5 46 24 PM" src="https://user-images.githubusercontent.com/3867506/94619995-df913300-027b-11eb-87f2-65ecf7cb6bfc.png">

<img width="196" alt="Screen Shot 2020-09-29 at 5 46 39 PM" src="https://user-images.githubusercontent.com/3867506/94620018-e8820480-027b-11eb-8de5-21a067cba147.png">
