### ISSUE TITLE
Switching away from using react-dnd decorators

### ISSUE THREAD

**Issue by OscarWoHA** [uptick/react-keyed-file-browser#124]
Hi! 

We've been having some issues with users crashing while switching from one route to another because the old DragAndDropContext creates a new backend on top of the previous one. 

Pretty sure moving away from the now called "legacy"/deprecated decorators will resolve the problems. I might be able to put some time into a PR for this exact change, let me know if that's wanted.

**Comment by jarekwg** [comment]
By all means, please!

Related: #27

**Comment by dreadera** [comment]
Closing as decorators have been removed.
