### ISSUE TITLE
Option to download folder

### ISSUE THREAD

**Issue by venky0195** [uptick/react-keyed-file-browser#150]
Hi, I'm unable to download a folder. However, download files is working.
 <FileBrowser 
onDownloadFile={arrayOfSelectedItems => { console.log('downloadFile', arrayOfSelectedItems) }}
onDownloadFolder={(arrayOfSelectedFolders) => { console.log('downloadFolder', arrayOfSelectedFolders) }} />
I'm getting console for onDownloadFile, but no download button when I click on folder.
Thanks in advance

**Comment by venky0195** [comment]
Also, there is only below code in browser.js in node modules.
actionRenderer: ActionRenderer,
onCreateFolder, onRenameFile, onRenameFolder,
onDeleteFile, onDeleteFolder, onDownloadFile

There is no onDownloadFolder anywhere in the browser.js

**Comment by mwfister** [comment]
Hi Venky, the latest release doesn't have the changes that includes the `onDownloadFolder`. I'm in the process of putting together a release. After it's released, if you still are having troubles, feel free to re-open this issue and we can look into it

**Comment by mwfister** [comment]
@venky0195 You can now update to `1.10.0` to use `onDownloadFolder`

**Comment by venky0195** [comment]
Thanks @mwfister !
