### ISSUE TITLE
Different style than on demo app

### ISSUE THREAD

**Issue by serek8** [uptick/react-keyed-file-browser#159]
Hey, the app seems to differ than the one on demo. I think it might be an issue with styles but no idea how to fix it. Here are the diffs:
* blue font
* different font style
* blue icons
<img width="745" alt="Screenshot 2020-12-28 at 00 50 41" src="https://user-images.githubusercontent.com/8598888/103181915-bf870500-48a6-11eb-98a5-b523753f4047.png">

**Comment by jlo-1** [comment]
Hi @serek8, the styles on the demo app are imported from the [uptick-demo-site](https://github.com/uptick/uptick-demo-site) repository.

You can see it being imported for the demo-site [here](https://github.com/uptick/react-keyed-file-browser/blob/master/demo-site/demos.sass)

You'll have to apply your own custom css to your application if you wish to customise the style of the file-browser past what is already implemented in this repo.

Cheers

**Comment by EPishchalnikov** [comment]
> You'll have to apply your own custom css to your application if you wish to customise the style of the file-browser past what is already implemented in this repo.

Hey, @jlo-1! Can you show some little showcase regarding applying custom css? For now, i see that some classes present in the source code are being deleted in resulting bundle, so it looks uncler how to customize styles.
For example i try to change text color of one of the action buttons, applying my style by class:
https://github.com/uptick/react-keyed-file-browser/blob/eb1bb8cacd479713dfa799c2ed5a381c426bac13/src/actions/default.js#L138
I created styles.css and imported it to my component:
![image](https://user-images.githubusercontent.com/62008532/105027338-af56e580-5a60-11eb-9687-e08f1df8243b.png)
But in the browser i see that corresponding DOM node doesn't have such class:
![image](https://user-images.githubusercontent.com/62008532/105027715-24c2b600-5a61-11eb-8b1b-c379ea94c234.png)
Any thoughts on this?

**Comment by jlo-1** [comment]
Hi @EPishchalnikov, the `Actions` component provided with the package is just a default, what i would suggest is creating your own `NewActions` component, copy the default into it as a start and then make modifications to it as you so please, from there you could add classnames wherever you need and apply styling.

Then, you can pass the new `NewActions` component into the FileBrowser component as a prop which will override the default.

Hope this helps
Cheers
