### ISSUE TITLE
handleFileClick as a prop ?

### ISSUE THREAD

**Issue by souuu** [uptick/react-keyed-file-browser#16]
Hello,
I can't find the handleFileClick function as a prop,
I need to detect the click on the file, so I can generate a download link at that time and edit the object.
How can I do this ?

**Comment by jarekwg** [comment]
Hi souuu,

You can extend `BaseFile` and give it your own `handleFileClick` functionality, then pass it in to the browser's `fileRenderer` prop.

Alternatively, we can make a tweak to allow passing this callback in through `fileRendererProps`. Happy to accept a PR that does this.

Cheers,

**Comment by souuu** [comment]
Hello jarekwg,
Thank you for that quick reply !

Can you help me with an example please ?
For example I want to do a console.log when the file is clicked.

Thank you.

**Comment by jarekwg** [comment]
```
class MyFile extends BaseFile {
  handleFileClick = (event) => {
    console.log(this.props.fileKey)
  }
}
```

```
<FileBrowser
  files=...
  ...
  fileRenderer=MyFile
  ...
/>
```

**Comment by souuu** [comment]
Hello jarekwg,
I have a problem doing this ..
if I do extends BaseFile , I have
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`
and if I do extends TableFile, I have
```
TypeError: Super expression must either be null or a function, not undefined
    at ./node_modules/babel-runtime/helpers/inherits.js.exports.default
```
Any Idea please ?

**Comment by jarekwg** [comment]
Make sure your loader understands decorators.
If you're using babel 6, add this plugin to get it working: `babel-plugin-transform-decorators-legacy`
https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy

**Comment by souuu** [comment]
Thank you for your support jarekwg,
but i have another error which is
`Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`
I think it's related to how i'm importing the module, I did all possible ways I think .. but no result ..
```
import FileBrowser from 'react-keyed-file-browser'
import {FileBrowser} from 'react-keyed-file-browser'
import FileBrowser from 'react-keyed-file-browser/dist/react-keyed-file-browser'
```

**Comment by souuu** [comment]
well, I have forced the updated babel-loader to compile the file,
now if i put  
` <FileBrowser files={filesList} fileRenderer={MyFile} />`
I have 
```
Uncaught TypeError: Cannot read property 'concat' of undefined
    at FileBrowser.render
```
exactly at :
```
value: function render() {
	      var _this3 = this;

	      var browserProps = this.getBrowserProps();
	      var headerProps = {
	        fileKey: '',
	        browserProps: browserProps
	      };
	      var renderedFiles = void 0;

	      **## var files = this.props.files.concat([]);**
	      if (this.state.activeAction === 'createFolder') {
	        files.push({
	          key: this.state.actionTarget,
	          size: 0,
	          draft: true
	        });
	      }
```

**Comment by jarekwg** [comment]
Regarding importing, you want:
`import FileBrowser from 'react-keyed-file-browser'`
or, if you need to wrap with your own dnd context, import the unwrapped version like this:
`import { RawFileBrowser as FileBrowser } from 'react-keyed-file-browser'`

Regarding your error, it's saying that `this.props.files` is undefined.
Have you passed files into the component? I'll update repo to mark that prop as required.
Minimal example:
https://github.com/uptick/react-keyed-file-browser/blob/master/demo-site/flat-simple.js

Cheers,

**Comment by MincedCutlet** [comment]
I think I'm correctly passing in the files to the component, but like souuu, the files are still not picked up if I use the fileRenderer. See this super simple example: https://codesandbox.io/s/w6r6o6ov5w

**Comment by jarekwg** [comment]
ooooh. Okay I see what's up. My apologies to @souuu for misunderstanding the issue.

You're trying to extend a component that has been decorated with DND context stuff.
This causes weirdness which results in props for TableFile getting fed into the FileBrowser component..

Solution is not to extend a component that has been DND decorated (ie TableFile).
You should either extend BaseFile, or gimme a minute and I'll push up a patch that exposes a `RawTableFile`, which is essentially just TableFile without the dnd decoration. Then, you can extend that, and decorate your extended component with DND yourself (if desired). See the example here:
https://codesandbox.io/s/m77vm9l6zp

Also, I've never used codesandbox before. It's very slick!

**Comment by jarekwg** [comment]
Done. I've edited my above example, to not be extending TableFile.
Lemme know if that works for you!

**Comment by Mr-Antivirus** [comment]
Hello, I tried the code you provided in the sandbox and it works perfectly fine there, however, I've been struggling to figure out why it doesn't work when I copy and paste exactly what you had there.

I finally realized that it is because the handleFileClick function is defined inside the class via an arrow function. If I change the definition to a normal class definition...

`class MyFile extends FileRenderers.RawTableFile {
  handleFileClick(event) {
    console.log("key " + this.props.fileKey)
  }
}`

Then the function doesn't get called and the default functionality happens. This can be easily solved by changing a webpack config to support es2016/es2017 functionality. But, I don't want additional changes to my current build setup. Is there an alternative way to accomplish this?

**Comment by jarekwg** [comment]
Hey Mr-Antivirus,

Not sure...
Arrow functions are awesome though, you probs want to be moving to use them anyway. :D

Sorry,

**Comment by ziaulrehman40** [comment]
With the sandbox example, i am getting: 

```
react-keyed-file-browser.js:1 Uncaught TypeError: this.props.connectDropTarget is not a function
    at MyFile.value (react-keyed-file-browser.js:1)
    at MyFile.value (react-keyed-file-browser.js:1)
    at finishClassComponent (react-dom.development.js:17184)
    at updateClassComponent (react-dom.development.js:17134)
    at beginWork (react-dom.development.js:18653)
```

**Comment by ziaulrehman40** [comment]
Ok, this is what happens when you don't have docs :smile: 

Download can be done with https://github.com/uptick/react-keyed-file-browser/issues/104
