### ISSUE TITLE
A couple questions on usage of this library

### ISSUE THREAD

**Issue by rvanheest** [uptick/react-keyed-file-browser#24]
Hi, thanks for creating this great and nice looking component! I've got a couple of questions before deciding whether we can use this in our application.

1. Currently this library has peerDependencies on React v0.14 and v15. Are there any plans to upgrade to React v16, which is the current version (and higher, as they are released in the future)?
2. The icons used for folders, files, etc. are based on an old version of FontAwesome (v4). Are there plans to upgrade to the newer version (v5)?
3. We would like to have our own custom columns in the table, which would include renaming the headers as well as displaying some dropdown fields in the 'file rows'.
    * I saw you had a great many hooks to customize the behavior of this library. However, I was not yet able to find hooks that would support renaming headers, adding columns, etc. Am I missing something?
    * One option I found was to use the `headerRenderer` prop and write a custom Header component, however, this would copy the whole `TableHeader` component in your implementation and rename some values. Similar for `fileRenderer`, of course. Is this the intended way of customizing the table? It doesn't seem particularly DRY.
    * I tried the above approach of copying and customizing the Header component, but once I add the `DropTarget` to the component, it doesn't show up anymore. Any clue as to why that is the case? Could this be the case because your library is on v2.x of `react-dnd` and `react-dnd-html5-backend`, while our's is on v5.x? If so, are there plans to upgrade?
4. I wasn't able to find any documentation except for the [live demo](https://uptick.github.io/react-keyed-file-browser/). Is there more documentation to be found? Until now I've tried to piece together the 'documentation' from reading the code itself.
5. We're using TypeScript in our project, so it would really help us out if there were some type definitions available. Do you have any plans for adding those in the future?

We would really like the component, but these are some of the problems we encountered with it so far. In general it would probably already help a lot if the dependencies could be upgraded. Usually I would try to contribute something here, but I'm not yet sure how much time I'll have for that in the upcoming months.

**Comment by jarekwg** [comment]
Hi Richard,

1. Yes, we will definitely be bumping the versions. We already use this package with react16, just haven't gotten round to bumping the package.json here to silence the warning...
2. No plans to bump to fontawesome 5 particularly soon, but it will happen eventually.
3. Sections of this package aren't as pluggable as others. Looks like you're right about the column definitions, for example. Seems like the only way currently is to replace the whole Header and Item Renderers with your own. The primary use case of this package is to offer a window into a keyed file system like S3. It doesn't aim to offer much more functionality than that. If you'd like to just display a list of things with customisable columns, you could look at react-table, or one of our other packages react-object-table (editable), react-object-list (readonly with advanced filtering). Currently there are no plans to bump react-dnd, but we'd likely end up doing it eventually.. 
4. Unfortunately there's no documentation aside from our live demo. Our team is a little too pressed for time to write up full docs. :(
5. No intention to support TypeScript, but this is all written in React, so we've got PropTypes defined at the component levels.

Thanks for showing interest! We use this package heavily in production, so it'll continue to be maintained for quite a while to come. This will include (eventual) updates to dependencies. We're generally pretty proactive with keeping things up to date, but of course we're happy to accept PRs to help push this forward too.

Cheers,
Jarek

**Comment by jarekwg** [comment]
React16 support is now listed in package.json in the 1.3.1 release.
Also, re fontawesome, we might end up stripping it out of here altogether and asking the user to feed their own icon mapping in. (More of a hassle, but makes it more open to competing icon libraries). No ETA on any of that though.

**Comment by jarekwg** [comment]
Closing this; opened issues #25, #26, #27, #28.
Thanks!

**Comment by rvanheest** [comment]
This all sounds great @jarekwg! Definitely gonna try it out once I get back from holiday.
