### ISSUE TITLE
Write up beefy docs.

### ISSUE THREAD

**Issue by jarekwg** [uptick/react-keyed-file-browser#25]

**Comment by ziaulrehman40** [comment]
Please layout some plan/instructions so people can help.
And we can start small, like in start we can mention that docs are incomplete, and after multiple PRs when docs are complete we can remove that warning.

**Comment by dreadera** [comment]
Closing as documentation will be updated as a part of the `typescript`PR #189  with the help of https://docusaurus.io/.
