### ISSUE TITLE
Bump react-dnd

### ISSUE THREAD

**Issue by jarekwg** [uptick/react-keyed-file-browser#27]
We're using a pretty old version now. On 2.1.4, latest is 5.x.
Time to upgrade!

**Comment by nsmithdev** [comment]
react-dnd version 3.0.2+ uses context which requires React 16+
https://github.com/react-dnd/react-dnd/issues/1101

Current version is now 9.3.2

**Comment by ziaulrehman40** [comment]
Current version is now 10, we really need to do something about this.

**Comment by ziaulrehman40** [comment]
I just checked and you can bump version to 8.x pretty much doing nothing, version 9+ requires switching to context api from decorators and HOCs

**Comment by jarekwg** [comment]
Happy to accept a PR!

**Comment by ziaulrehman40** [comment]
@jarekwg PR is up

**Comment by jarekwg** [comment]
Cheers, we'll get someone to review and publish soon!
