### ISSUE TITLE
Question about separating folders, files, and information.

### ISSUE THREAD

**Issue by Okami-** [uptick/react-keyed-file-browser#30]
I have a design that has folders on the first column, files in the middle column and the file information on the third column. Is there a way to separate the 3 into distinct columns and still have the interactivity? For example I would click the folder on the first column and the listing of the files inside the folder from the first column would display on the second column.

**Comment by jarekwg** [comment]
Hey Okami- 

The default renderers don't offer this sort of behaviour.
You _should_ be able to get whatever layout you want with custom renderers, as what you're going for sounds functionally the same.
If renderers seem like they're too restrictive, try forking the repo first, change the code around until it works, then work backwards from there, trying to contain your changes to custom Renderers.
We're happy to accept PRs that let custom renderers do more, if you need that.

Cheers,
