### ISSUE TITLE
Question: can i change the details view for images

### ISSUE THREAD

**Issue by badris101** [uptick/react-keyed-file-browser#33]
i want to change the details view for images i want the image to show up
![sans titre](https://user-images.githubusercontent.com/32427487/47640676-03154580-db5c-11e8-9467-cb12c8947fee.png)

**Comment by jarekwg** [comment]
You sure can!
Spin up your own detail renderer and pass it, along with additional props of your choosing (eg callback methods) to the FileBrowser like so:
```
<FileBrowser
  ...
  detailRenderer={myDetailRenderer}
  detailRendererProps={myDetailRendererProps}
>
```
We use a popup modal for our detail renderer, though it hasn't been included in this package as it does some heavy stuff (rendering pdfs, xlsx files, etc).

**Comment by battistone** [comment]
To expand on this, here's a custom detail renderer you can use to just display an image:

`import React from 'react';
import { connect } from 'react-redux';
export class CustomDetailRenderer extends React.Component {
    constructor(props) {
      super(props)
    }
    render() {
      return (
        <div>
          {checkIfImage(this.props.file.extension) && <img src={this.props.file.url}></img>}
        </div>
      );
    }
  }

  function checkIfImage(fileextension)
{
    let IsFiletypeAllowed = false;
    const extensions = [
    "jpg","jpeg","tif","tiff","gif","png",
    ]
    const fileType = fileextension.toLowerCase();
    IsFiletypeAllowed = extensions.includes(fileType);

    return IsFiletypeAllowed;

}
  export default CustomDetailRenderer;`

**Comment by jarekwg** [comment]
Nice! Yeah, custom props is more for stuff like passing in a callback to close the preview.

**Comment by ThomiReynoso** [comment]
> You sure can!
> Spin up your own detail renderer and pass it, along with additional props of your choosing (eg callback methods) to the FileBrowser like so:
> 
> ```
> <FileBrowser
>   ...
>   detailRenderer={myDetailRenderer}
>   detailRendererProps={myDetailRendererProps}
> >
> ```
> 
> We use a popup modal for our detail renderer, though it hasn't been included in this package as it does some heavy stuff (rendering pdfs, xlsx files, etc).


Hi @jarekwg, could you give me an example of how to implement my `CustomDetailRender` to be able to pass my own props to this? 
I guess that my own props needs to be declarared inside the object that is sent on `file` attribute:

```
let files = {
    fullKey: ...,
    key: ...,
    modified: ...,
    size: ...,
    url: ...,
  }; 
```
Where `fullKey` is my own prop.

And then 
```
<FileBrowser
            files={files}
            detailRendererProps={CustomDetailRender}
           ....
/>
```
How can I receive these own props in the `CustomDetailRender.js` component?


Thanks you!

**Comment by jarekwg** [comment]
Define like this:
```
<FileBrowser
  ...
  detailRenderer={myDetailRenderer}
  detailRendererProps={myDetailRendererProps}
>
```

The file browser will spread your props into your detail renderer on your behalf:
https://github.com/uptick/react-keyed-file-browser/blob/d0e9bf0824ef89bde2b3a1123bebf696a7108ea8/src/browser.js#L715-L719
