### ISSUE TITLE
onMoveFile and onMoveFolder props are not triggered

### ISSUE THREAD

**Issue by raniel90** [uptick/react-keyed-file-browser#49]
Hi,

the funcionts onMoveFile and onMoveFolder are not triggered.

`handleMoveFolder = (oldKey, newKey) => {
    console.log('handleMoveFolder', oldKey, newKey) //not working
  }`

`
handleMoveFile = (oldKey, newKey) => {
    console.log('handleMoveFile', oldKey, newKey); //not working
}`

`
 onRenameFolder={this.handleRenameFolder}
`
`
 onRenameFile={this.handleRenameFile}
`

**Comment by jlo-1** [comment]
Thanks @raniel90 !
Merged via https://github.com/uptick/react-keyed-file-browser/pull/50
