### ISSUE TITLE
[Feature Request] Support Multiple instance.

### ISSUE THREAD

**Issue by lh-hoon** [uptick/react-keyed-file-browser#54]
When I use more than one component, I got error 'Cannot have two HTML5 backends at the same time.'

**Comment by lh-hoon** [comment]
My mistake.. 😂

**Comment by jarekwg** [comment]
Nah, legit question.
Use the `RawFileBrowser` instead, and wrap with html5 backend yourself. We have a special html decorator, which we use to make sure all things that need html5 backend use the same one.
