### ISSUE TITLE
Folder/file onclick?

### ISSUE THREAD

**Issue by kkseven07** [uptick/react-keyed-file-browser#62]
How to make a trigger for onClick on folder and file? Checked similar issues, found one example from the author, but that example was not addressed to my question fully.
I'm using FileRenderer and FolderRenderer to make custom file and folder components. How can I access onClick there?

**Comment by kkseven07** [comment]
I need folder onClick to load the files of this folder when it expands

**Comment by irosadie** [comment]
please use props onSelect, filter by "undefined" for folder or object for file

**Comment by scaredcat** [comment]
We also have `onSelectFolder` and `onSelectFile` props available if you only want to trigger a load when a folder is selected.

Please re-open the issue if this does not solve your problem.

**Comment by shamseerahammedm** [comment]
onSelectFolder  and onSelectFile is not documented
