### ISSUE TITLE
how to upload files  

### ISSUE THREAD

**Issue by takifouhal** [uptick/react-keyed-file-browser#70]
when i drag&drop files they get added to the ui but i don't know what function get invocked

**Comment by scaredcat** [comment]
Hi @takifouhal ,
I believe you're looking for the `onCreateFiles` and `onCreateFolder` props passed into the browser.

```javascript
const onCreateFiles = (files, prefix) => { console.log('creating files', files, 'with prefix', prefix) }
```

```javascript
const onCreateFolder = (fkey) => { console.log('creating folder at ', key) }
```

And then when you instantiate a new file browser you can pass them in like
```jsx
<FileBrowser
 onCreateFiles={onCreateFiles}
 onCreateFolder={onCreateFolder}
 {...otherProps}
/>
```

Let me know if this helps.

**Comment by ziaulrehman40** [comment]
@scaredcat I am looking for an example of upload file with some kind of progress bar to indicate to user. progress of each file being uploaded.
Is there an example available for that?

Thanks.

**Comment by scaredcat** [comment]
Hi @ziaulrehman40 right now we don't have that as part of this repository. It is a bit of an oversight and can be included in the future. Currently you'd want to follow these general steps:

1. Create a component that renders the progress bar
2. Create a function that uploads files and tracks the progress using something like the `progress` event listener (see https://codepen.io/PerfectIsShit/pen/zogMXP for an example)
3. Pass in this handler to the `onCreateFiles` prop which will then use your code for uploading and displaying a loading bar.

**Comment by adisaxena09** [comment]
when the user clicks on any folder say **documents/photos** then I want the file upload option instead of drag and drop is it possible? If not what is the workaround.
